language: java
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
addons:
  sonarqube: true
script: mvn -DskipITs=true -DindentSize=4 clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar