language: java
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
addons:
  sonarqube: true
script:
    - 'if [ ${TRAVIS_SECURE_ENV_VARS} = "true" ]; then
          mvn -DindentSize=4 clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
      else
          mvn clean install
      fi'